- name: Install Java 8 Pre-Requisites
  apt: name=python-software-properties
  
- name: Add Java 8 Repository
  apt_repository: repo='ppa:webupd8team/java'
  
- name: Agree to Oracle Licence
  debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true
  
- name: Install Java 8
  apt: name=oracle-java8-installer state=latest force=yes update_cache=yes
